### ISSUE TITLE
Errors encountered while trying to build

### ISSUE THREAD

**Issue by thepilot21** [panodata/panodata-map-panel#124]
Hello, I want to experiment with some enhancements to your excellent panel. I have cloned the project to my local machine (running Ubuntu 20.04 ) nto a folder under plugins. I then tried to follow the instructions in CONTRIBUTING.md. However, no matter what I try I get and error 

Bundling plugin in dev mode  Trace: SyntaxError: /home/mike/grafana-plugins/panodata-map-panel/src/plugin.json: Unexpected token { in JSON at position 648
Seems to point to plugin.json but that has far fewer than 648 line :-(.
The whole error message is as follows and I wonder if you can give me any insight into what's causing because two days of investigation have got me know where.

ike@mike-Virtual-Machine:~/grafana-plugins/panodata-map-panel$ npx grafana-toolkit plugin:dev
✔ Linting
⠋ Bundling plugin in dev mode  Trace: SyntaxError: /home/mike/grafana-plugins/panodata-map-panel/src/plugin.json: Unexpected token { in JSON at position 648
      at parse (<anonymous>)
      at Object.Module._extensions..json (node:internal/modules/cjs/loader:1135:22)
      at Module.load (node:internal/modules/cjs/loader:972:32)
      at Function.Module._load (node:internal/modules/cjs/loader:813:14)
      at Module.require (node:internal/modules/cjs/loader:996:19)
      at require (node:internal/modules/cjs/helpers:92:18)
      at Object.exports.getPluginId (/home/mike/grafana-plugins/panodata-map-panel/node_modules/@grafana/toolkit/src/config/utils/getPluginId.js:9:26)
      at Object.exports.getFileLoaders (/home/mike/grafana-plugins/panodata-map-panel/node_modules/@grafana/toolkit/src/config/webpack/loaders.js:156:64)
      at /home/mike/grafana-plugins/panodata-map-panel/node_modules/@grafana/toolkit/src/config/webpack.plugin.config.js:260:38
      at step (/home/mike/grafana-plugins/panodata-map-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:140:27)
      at Object.next (/home/mike/grafana-plugins/panodata-map-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:121:57)
      at fulfilled (/home/mike/grafana-plugins/panodata-map-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:111:62)
      at /home/mike/grafana-plugins/panodata-map-panel/node_modules/@grafana/toolkit/src/cli/utils/useSpinner.js:25:29
      at step (/home/mike/grafana-plugins/panodata-map-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:140:27)
      at Object.throw (/home/mike/grafana-plugins/panodata-map-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:121:57)
      at rejected (/home/mike/grafana-plugins/panodata-map-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:112:69)
✖ /home/mike/grafana-plugins/panodata-map-panel/src/plugin.json: Unexpected token { in JSON at position 648
mike@mike-Virtual-Machine:~/grafana-plugins/panodata-map-panel$ 

Many thanks in advance.

Mike

**Comment by amotl** [comment]
Dear Mike,

thank you very much for reporting this issue. It was my fault, 65f99628 fixes the `plugin.json` file again. Apologies for the hiccup!

With kind regards,
Andreas.

**Comment by thepilot21** [comment]
Thanks for the quick response Andreas.

I can confirm that this fixes the problem.

Closing.

Mike
